name: zammad
description: Zammad is a web based open source helpdesk/customer support system
homepage: https://zammad.org
notifications: false
targets:
  ubuntu-22.04:
    dependencies:
      - curl
      - elasticsearch|elasticsearch-oss
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server
      - libimlib2
      - shared-mime-info
      - redis-server
    build_dependencies:
      - libimlib2
      - libimlib2-dev
      - shared-mime-info
before:
  - contrib/packager.io/before.sh
after:
  - contrib/packager.io/after.sh
env:
  - RAILS_ENV=production
  - ZAMMAD_BIND_IP=127.0.0.1
  - ZAMMAD_RAILS_PORT=3000
  - ZAMMAD_WEBSOCKET_PORT=6042
services:
  - postgres:15
  - redis
before_install: contrib/packager.io/preinstall.sh
after_install: contrib/packager.io/postinstall.sh
buildpack: https://github.com/pkgr/heroku-buildpack-ruby.git#v267-1